/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.swing;

import api.looca.ApiLooca;
import com.sun.jdi.DoubleValue;
import conexao.azure.Connector;
import conexao.azure.ConnectionLocal;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 *
 * @author joao_
 */
public class TelaMonitoramento extends javax.swing.JFrame {

   
        
    Connector config = new Connector();
    ApiLooca dados = new ApiLooca();
    JdbcTemplate con = new JdbcTemplate(config.getDataSource());

    Double usoProcessador = 0.0;
    Double usoRam = 0.0;
    Double usoDisco1 = 0.0;
    Double totalDiscoDisponivel1 = 0.0;

    Double usoDisco2 = 0.0;
    Double totalDisco2 = 0.0;
    Double totalDiscoDisponivel2 = 0.0;

    Double totalRamDisponivel = 0.0;

    String data = "";

    /**
     * Creates new form TelaMonitoramento
     */
    public TelaMonitoramento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelCPU = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelDisco1 = new javax.swing.JLabel();
        jProgressBarDisco1 = new javax.swing.JProgressBar();
        jLabelStatusDisco1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelDisco2 = new javax.swing.JLabel();
        jProgressBarDisco2 = new javax.swing.JProgressBar();
        jLabel12 = new javax.swing.JLabel();
        jLabelStatusDisco2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMemoria = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(56, 12, 42));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(146, 44, 112));
        jPanel2.setName(""); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CPU");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, -1));

        jLabelCPU.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabelCPU.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCPU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCPU.setText("0,0%");
        jPanel2.add(jLabelCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 340, 130));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 360, 200));

        jPanel3.setBackground(new java.awt.Color(146, 44, 112));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DISCO 1");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.mycompany.imagens/id=68429-format=pngHD.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 260, 90));

        jLabelDisco1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelDisco1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDisco1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDisco1.setText("Obtendo dados...");
        jPanel3.add(jLabelDisco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 260, 50));

        jProgressBarDisco1.setForeground(new java.awt.Color(1, 1, 1));
        jProgressBarDisco1.setStringPainted(true);
        jPanel3.add(jProgressBarDisco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 250, -1));

        jLabelStatusDisco1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabelStatusDisco1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelStatusDisco1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStatusDisco1.setText("INATIVO");
        jPanel3.add(jLabelStatusDisco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 160, 70));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Status:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 90, 70));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 280, 410));

        jPanel4.setBackground(new java.awt.Color(146, 44, 112));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DISCO 2");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.mycompany.imagens/id=68429-format=pngHD.png"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 250, 90));

        jLabelDisco2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelDisco2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDisco2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDisco2.setText("Obtendo dados...");
        jPanel4.add(jLabelDisco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 240, 50));

        jProgressBarDisco2.setForeground(new java.awt.Color(1, 1, 1));
        jProgressBarDisco2.setStringPainted(true);
        jPanel4.add(jProgressBarDisco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 230, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Status:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 90, 70));

        jLabelStatusDisco2.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabelStatusDisco2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelStatusDisco2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStatusDisco2.setText("INATIVO");
        jPanel4.add(jLabelStatusDisco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 150, 70));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 270, 410));

        jPanel5.setBackground(new java.awt.Color(146, 44, 112));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("COMEÇAR");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 60));

        jPanel5.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, 60));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 270, 100));

        jPanel6.setBackground(new java.awt.Color(146, 44, 112));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MEMÓRIA");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, -1));

        jLabelMemoria.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabelMemoria.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMemoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMemoria.setText("0,0%");
        jPanel6.add(jLabelMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 340, 120));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 360, 190));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CineSolution™");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 550, 110, -1));

        jPanel11.setBackground(new java.awt.Color(146, 44, 112));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SISTEMA OPERACIONAL");
        jPanel11.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Obtendo dados...");
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 260, 40));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 280, 100));

        jPanel12.setBackground(new java.awt.Color(146, 44, 112));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PROCESSADOR");
        jPanel12.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Obtendo dados...");
        jPanel12.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 340, 40));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 360, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        
        Connector local;
        
        usoProcessador = dados.usoProcessador();
        usoRam = dados.usoRam();
        usoDisco1 = dados.usoDisco1();
        usoDisco2 = dados.usoDisco2();
        totalDiscoDisponivel1 = dados.totalDisco1();
        totalDiscoDisponivel2 = dados.totalDisco2();
        totalRamDisponivel = dados.totalDisponivelRam();
        data = dados.data();

        jLabelCPU.setText(String.format("%.1f", usoProcessador) + "%");
        jLabelMemoria.setText(String.format("%.1f", usoRam) + "%");
        if (dados.totalDisco1() > 0) {
            jLabelDisco1.setText(String.format("%.2fGB livre do total de %.2fGB", dados.totalDisponivelDisco1(), dados.totalDisco1()));
            jLabelStatusDisco1.setText("ATIVO");
            jLabelStatusDisco1.setForeground(Color.green);
            int IntValue = (int) Math.round(usoDisco1);
            jProgressBarDisco1.setValue(IntValue);
            jProgressBarDisco1.setString(String.valueOf(IntValue) + "%");
            jProgressBarDisco1.setStringPainted(true);

        } else {
            jLabelStatusDisco1.setText("INATIVO");
            jLabelStatusDisco1.setForeground(Color.red);
        }
        if (dados.totalDisco2() > 0) {
            jLabelDisco2.setText(String.format("%.2fGB livre do total de %.2fGB", dados.totalDisponivelDisco1(), dados.totalDisco1()));
            jLabelStatusDisco2.setText("ATIVO");
            jLabelStatusDisco2.setForeground(Color.green);
            int IntValue = (int) Math.round(usoDisco2);
            jProgressBarDisco2.setValue(IntValue);
            jProgressBarDisco2.setString(String.valueOf(IntValue) + "%");
            jProgressBarDisco2.setStringPainted(true);

        } else {
            jLabelStatusDisco2.setText("INATIVO");
            jLabelStatusDisco2.setForeground(Color.red);
        }
        jLabel11.setText(dados.nomeSistemaOperacional());
        jLabel14.setText(dados.nomeProcessador());

        System.out.println("inserindo dados...");
        //INSERT NO BANCO DE DADOS
        con.update("INSERT INTO tb_uso values (?,?,?,?,?,?,?,0,0)",
                usoProcessador,
                usoDisco1,
                totalDiscoDisponivel1,
                usoRam,
                totalRamDisponivel,
                data,
                16
    
        );
        try {
            // create a mysql database connection
            Connection conexao;
            
            ConnectionLocal conexaoLocal = new ConnectionLocal();
            conexao=conexaoLocal.getDataSource();
            
            PreparedStatement stn = null;
            ResultSet result = null;

            String query = "insert into tb_uso ( uso_processador, uso_disco, disco_disponivel, uso_ram, ram_disponivel, data_uso, fk_maquina, uso_disco2, disco_disponivel2) values (?,?,?,?,?,?,?,0,0)";

            
            stn =conexao.prepareStatement(query);
            
            stn.setDouble(1, usoProcessador);
            stn.setDouble(2, usoDisco1);
            stn.setDouble(3, totalDiscoDisponivel1);
            stn.setDouble(4, usoRam);
            stn.setDouble(5, totalRamDisponivel);
            stn.setString(6, data);
            stn.setInt(7, 1);         
            

            // execute the preparedstatement
            stn.execute();

            } catch (Exception e) {
            System.err.println("Got an exception!");
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMonitoramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMonitoramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMonitoramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMonitoramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMonitoramento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCPU;
    private javax.swing.JLabel jLabelDisco1;
    private javax.swing.JLabel jLabelDisco2;
    private javax.swing.JLabel jLabelMemoria;
    private javax.swing.JLabel jLabelStatusDisco1;
    private javax.swing.JLabel jLabelStatusDisco2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JProgressBar jProgressBarDisco1;
    private javax.swing.JProgressBar jProgressBarDisco2;
    // End of variables declaration//GEN-END:variables
}
